[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.run]
dependencies = [
    "format",
    "build"
]
command = "cargo"
args = ["run"]

[tasks.train]
command = "cargo"
args = ["run", "--bin", "training"]
